%%% wrapper for plot_resp_timecourse.m specific to DAF project
 % resp = a single electrode's row from the resp table generated by response_types_daf.m
 % trials = trialtable generated for the subject that the electrode, also generated by response_types_daf.m

function [trials,resp_grpd, align_stats, op_out] = plot_resp_timecourse_daf(resp, trials, op)

% close all

 %% params 
 vardefault('op',struct) ;


field_default('op','sort_cond',[]); % if empty, don't separate traces by trial characteristics
%     field_default('op','sort_cond','delay');

field_default('op','condval_inds_to_plot', []); % plot all vals

field_default('op','newfig',1);
field_default('op','smooth_timecourses', 1);
field_default('op','smooth_method','gaussian');
field_default('op','smooth_windowsize',10);
field_default('op','ylimits', []); % use defaults
field_default('op','xlimits',[]);
field_default('op','trace_width',1);

%%%%% trial table varname for times used for time-locking responses
field_default('op','time_align_var','t_prod_on'); % default to speech onset

%%%% how to find the time length that trials will be cut/padded to be
field_default('op','trial_time_adj_method','median_plus_sd'); % median plus stdev
% field_default('op','trial_time_adj_method','median');
% field_default('op','trial_time_adj_method','max');

field_default('op','leg_pos_adjust',0.22); % move legend position to the left this much

%%%%%% end params
%%
% op.times_to_plot = table(op.times_to_plot(:,1), op.times_to_plot(:,2), op.times_to_plot(:,3), op.times_to_plot(:,4), 'VariableNames', {'varname','color','plot_label','line_side'}); 

op.sub = resp.sub{1}; 
trials.resp_unaligned = resp.timecourse{1};

 %% sort trials by condition, get average responses + error, plot
[trials,resp_grpd, align_stats, op_out] = plot_resp_timecourse(trials, op); % from ieeg_ft_funcs_am repo - must be on path

%%

if string(resp.type{1})=="ECOG"
    htitle = title([op.sub, '_', resp.chan{1}, '_area-', resp.HCPMMP1_label_1{1}], 'Interpreter','none');
else
    htitle = title([op.sub, '_', resp.chan{1}, '_area-', resp.DISTAL_label_1{1}], 'Interpreter','none');
end

     
f=get(gca,'Children');

if ~isempty(op.sort_cond)
    nvals_to_plot =  length(op.condval_inds_to_plot); 
    hleg = legend(flipud(f(end-nvals_to_plot+1:end)),resp_grpd.condval{op.condval_inds_to_plot});
    hleg.Position(1) = hleg.Position(1)-op.leg_pos_adjust; % move to the left
end
